# Generated by Django 5.2 on 2025-06-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltycard',
            name='number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
