# Generated by Django 5.2 on 2025-06-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gender_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='penalty',
        ),
    ]
