# Generated by Django 5.2 on 2025-05-17 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_alter_fuelinfo_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='address',
        ),
        migrations.AddField(
            model_name='station',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.TextField(choices=[('92', '92'), ('95', '95'), ('98', '98'), ('DT', 'DT')], max_length=2)),
                ('amount', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='stations.station')),
            ],
            options={
                'unique_together': {('station', 'fuel_type')},
            },
        ),
        migrations.AddField(
            model_name='station',
            name='gas_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='stations.gasstation'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FuelInfo',
        ),
    ]
