# Generated by Django 5.2 on 2025-05-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_gasstation_remove_station_address_station_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
