# Generated by Django 5.2 on 2025-05-17 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_station_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('busy_offline', 'Busy offline'), ('busy_online', 'Busy online'), ('free', 'Free'), ('not_working', 'Not working')], default='free', max_length=32),
        ),
        migrations.CreateModel(
            name='GasStationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('fuel_type', models.CharField(choices=[('92', '92'), ('95', '95'), ('98', '98'), ('DT', 'DT')], max_length=2)),
                ('fuel_amount', models.PositiveIntegerField()),
                ('car_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('loyalty', 'Loyalty')], max_length=10)),
                ('payment_key', models.TextField(blank=True, null=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='stations.station')),
            ],
        ),
    ]
