# Generated by Django 5.2 on 2025-06-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_gasstationlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasstationlog',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='gasstationlog',
            name='bonuses_used',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
